"""Extract Kenney's supplied UI tiles without changing their artwork."""
from pathlib import Path
from PIL import Image
root = Path(__file__).resolve().parents[1]
source = root / 'assets/packs/kenney-ui'
out = root / 'assets/game/ui'
out.mkdir(parents=True, exist_ok=True)
skins = {'green': 'Colored/green', 'greenPressed': 'Colored/green_pressed', 'grey': 'Colored/grey', 'greyPressed': 'Colored/grey_pressed', 'panel': 'Ancient/white', 'inlay': 'Ancient/white_inlay', 'blue': 'Colored/blue', 'red': 'Colored/red'}
registry = []
for name, path in skins.items():
    im = Image.open(source / f'9-Slice/{path}.png')
    w,h = im.size
    xs,ys = [0,4,w-4,w],[0,4,h-4,h]
    files = []
    for y in range(3):
        for x in range(3):
            tile=im.crop((xs[x],ys[y],xs[x+1],ys[y+1]))
            tile.resize((tile.width*2,tile.height*2),Image.Resampling.NEAREST).save(out/f'{name}-{y*3+x}.png')
            files.append(f"require('../../assets/game/ui/{name}-{y*3+x}.png')")
    registry.append(f"  {name}: [{', '.join(files)}],")
sheet=Image.open(source/'Spritesheet/UIpackSheet_transparent.png')
icons={'up':(396,414),'down':(414,414),'left':(396,432),'right':(414,432)}
for name,(x,y) in icons.items():
    sheet.crop((x,y,x+16,y+16)).resize((32,32),Image.Resampling.NEAREST).save(out/f'{name}.png')
(root/'src/constants/ui-skins.ts').write_text('// Generated by scripts/extract-ui.py from the supplied Kenney pack.\nexport const uiSkins = {\n'+'\n'.join(registry)+'\n};\nexport const uiArrows = {\n'+''.join(f"  {name}: require('../../assets/game/ui/{name}.png'),\n" for name in icons)+'};\n')
